# Deployment of Nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: website
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: website-content
        image: alpine/git
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/gcpmensch/tr-001.git && cp /tr-001/* /usr/share/nginx/html"]
        volumeMounts:  
        - name: html
          mountPath: "/usr/share/nginx/html"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: html-pvc

---
# PVC for index.html
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # This is the default storage class for GKE
---

# LoadBalancer service for Nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: website
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: LoadBalancer
